"""
This type stub file was generated by pyright.
"""

import sys
from typing import TYPE_CHECKING
from ._aaxis import Aaxis
from ._baxis import Baxis
from ._font import Font
from ._legendgrouptitle import Legendgrouptitle
from ._stream import Stream
from . import aaxis, baxis, legendgrouptitle

if TYPE_CHECKING:
    ...
else:
    ...
