"""
This type stub file was generated by pyright.
"""

import sys
from typing import TYPE_CHECKING
from ._colorscale import Colorscale
from ._hoverlabel import Hoverlabel
from ._line import Line
from . import hoverlabel

if TYPE_CHECKING:
    ...
else:
    ...
