"""
This type stub file was generated by pyright.
"""

import sys
from typing import TYPE_CHECKING
from ._decreasing import Decreasing
from ._hoverlabel import Hoverlabel
from ._increasing import Increasing
from ._legendgrouptitle import Legendgrouptitle
from ._line import Line
from ._stream import Stream
from . import decreasing, hoverlabel, increasing, legendgrouptitle

if TYPE_CHECKING:
    ...
else:
    ...
