"""
This type stub file was generated by pyright.
"""

import sys
from typing import TYPE_CHECKING
from ._font import Font
from ._grouptitlefont import Grouptitlefont

if TYPE_CHECKING:
    ...
else:
    ...
