"""
This type stub file was generated by pyright.
"""

import sys
from typing import TYPE_CHECKING
from ._angularaxis import AngularAxis
from ._domain import Domain
from ._radialaxis import RadialAxis
from . import angularaxis, radialaxis

if TYPE_CHECKING:
    ...
else:
    ...
