"""
This type stub file was generated by pyright.
"""

import sys
from typing import TYPE_CHECKING
from ._decreasing import Decreasing
from ._font import Font
from ._increasing import Increasing

if TYPE_CHECKING:
    ...
else:
    ...
