"""
This type stub file was generated by pyright.
"""

from _plotly_utils.importers import relative_import
from typing import TYPE_CHECKING
from ._kaleido import defaults, full_figure_for_development, get_chrome, to_image, write_image, write_images
from . import base_renderers, json, kaleido, orca
from ._json import from_json, read_json, to_json, write_json
from ._templates import templates, to_templated
from ._html import to_html, write_html
from ._renderers import renderers, show

if TYPE_CHECKING:
    ...
else:
    ...
