"""
This type stub file was generated by pyright.
"""

class _Defaults:
    """
    Class to store default settings for image generation.
    """
    def __init__(self) -> None:
        ...
    


defaults = ...
