"""
This type stub file was generated by pyright.
"""

from typing import List

def validate_coerce_fig_to_dict(fig, validate): # -> dict[str, list[Any] | Any] | dict[Any, Any]:
    ...

def validate_coerce_output_type(output_type): # -> type[Figure] | type[FigureWidget]:
    ...

def broadcast_args_to_dicts(**kwargs: dict) -> List[dict]:
    """
    Given one or more keyword arguments which may be either a single value or a list of values,
    return a list of keyword dictionaries by broadcasting the single valuesacross all the dicts.
    If more than one item in the input is a list, all lists must be the same length.

    Parameters
    ----------
    **kwargs: dict
        The keyword arguments

    Returns
    -------
    list of dicts
        A list of dictionaries

    Raises
    ------
    ValueError
        If any of the input lists are not the same length
    """
    ...

def plotly_cdn_url(cdn_ver=...): # -> str:
    """Return a valid plotly CDN url."""
    ...

