"""
This type stub file was generated by pyright.
"""

import sys
from typing import TYPE_CHECKING
from ._marker import Marker
from ._textfont import Textfont

if TYPE_CHECKING:
    ...
else:
    ...
