"""
This type stub file was generated by pyright.
"""

import sys
from typing import TYPE_CHECKING
from ._colorbar import ColorBar
from ._contours import Contours
from ._legendgrouptitle import Legendgrouptitle
from ._line import Line
from ._stream import Stream
from . import colorbar, contours, legendgrouptitle

if TYPE_CHECKING:
    ...
else:
    ...
