"""
This type stub file was generated by pyright.
"""

DERIVED_CLASSES = ...
class ValidatorCache:
    _cache = ...
    _json_cache = ...
    @staticmethod
    def get_validator(parent_path, prop_name):
        ...
    


